apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: test-pv 
spec: 
  capacity: 
    storage: 50Gi 
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce 
  csi: 
    driver: ebs.csi.aws.com 
    volumeHandle: vol-05786ec9ec9526b67 
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: ebs-claim 
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 50Gi 
--- 
apiVersion: v1 
kind: Pod 
metadata: 
  name: app 
spec: 
  containers: 
    - name: app 
      image: centos 
      command: ["/bin/sh"] 
      args: 
        ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"] 
      volumeMounts: 
        - name: persistent-storage 
          mountPath: /data 
  volumes: 
    - name: persistent-storage 
      persistentVolumeClaim: 
        claimName: ebs-claim